[2025-05-24T16:49:42.104+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T16:49:42.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:44:30+00:00 [queued]>
[2025-05-24T16:49:42.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:44:30+00:00 [queued]>
[2025-05-24T16:49:42.143+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-24T16:49:42.158+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-24 16:44:30+00:00
[2025-05-24T16:49:42.172+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2025) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-24T16:49:42.174+0000] {standard_task_runner.py:63} INFO - Started process 2034 to run task
[2025-05-24T16:49:42.170+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'medical_slm_pipeline', 'extract_data', 'manual__2025-05-24T16:44:30+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/medslm.py', '--cfg-path', '/tmp/tmp16pfsqva']
[2025-05-24T16:49:42.175+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_data
[2025-05-24T16:49:42.192+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-24T16:49:42.235+0000] {task_command.py:426} INFO - Running <TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:44:30+00:00 [running]> on host f688730305ed
[2025-05-24T16:49:42.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medical_slm_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T16:44:30+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T16:44:30+00:00'
[2025-05-24T16:49:42.315+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T16:49:42.328+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T16:49:42.329+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/medslm.py", line 31, in extract_data
    raise FileNotFoundError(f"{DATA_PATH} not found.")
FileNotFoundError: /opt/***/data/med_abstracts.json not found.
[2025-05-24T16:49:42.342+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=medical_slm_pipeline, task_id=extract_data, run_id=manual__2025-05-24T16:44:30+00:00, execution_date=20250524T164430, start_date=20250524T164942, end_date=20250524T164942
[2025-05-24T16:49:42.355+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task extract_data (/opt/***/data/med_abstracts.json not found.; 2034)
[2025-05-24T16:49:42.390+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T16:49:42.410+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T16:49:42.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
