[2025-05-24T16:41:44.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T16:41:44.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:41:37+00:00 [queued]>
[2025-05-24T16:41:44.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:41:37+00:00 [queued]>
[2025-05-24T16:41:44.153+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-24T16:41:44.166+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-24 16:41:37+00:00
[2025-05-24T16:41:44.183+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1647) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-24T16:41:44.182+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'medical_slm_pipeline', 'extract_data', 'manual__2025-05-24T16:41:37+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/medslm.py', '--cfg-path', '/tmp/tmp_qdpw3qc']
[2025-05-24T16:41:44.185+0000] {standard_task_runner.py:63} INFO - Started process 1656 to run task
[2025-05-24T16:41:44.185+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask extract_data
[2025-05-24T16:41:44.204+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-24T16:41:44.245+0000] {task_command.py:426} INFO - Running <TaskInstance: medical_slm_pipeline.extract_data manual__2025-05-24T16:41:37+00:00 [running]> on host f688730305ed
[2025-05-24T16:41:44.332+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='medical_slm_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T16:41:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T16:41:37+00:00'
[2025-05-24T16:41:44.334+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T16:41:44.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T16:41:44.374+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/medslm.py", line 31, in extract_data
    raise FileNotFoundError(f"{DATA_PATH} not found.")
FileNotFoundError: /opt/***/data/med_abstracts.json not found.
[2025-05-24T16:41:44.388+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=medical_slm_pipeline, task_id=extract_data, run_id=manual__2025-05-24T16:41:37+00:00, execution_date=20250524T164137, start_date=20250524T164144, end_date=20250524T164144
[2025-05-24T16:41:44.403+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task extract_data (/opt/***/data/med_abstracts.json not found.; 1656)
[2025-05-24T16:41:44.440+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T16:41:44.464+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T16:41:44.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
